import pyautogui
import time

datainicio= input("escreva a data de inicio: ")
datafim= input("escreva a data de fim: ")
 

#nw1
pyautogui.click(pyautogui.locateCenterOnScreen('imagem_1.png', confidence=0.8))
time.sleep(4)
pyautogui.click(pyautogui.locateCenterOnScreen('imagem_2.png', confidence=0.8))
time.sleep(4)
pyautogui.hotkey('ctrl', 'l')
time.sleep(6)
pyautogui.click(pyautogui.locateCenterOnScreen('imagem_3.png', confidence=0.8))
time.sleep(4)
pyautogui.write('Textdown:XXINVM', interval=0.1)
time.sleep(4)
pyautogui.press('enter')
time.sleep(4)
pyautogui.press('enter')
time.sleep(4)
pyautogui.press('enter')
time.sleep(4)
pyautogui.click(pyautogui.locateCenterOnScreen('imagem_6.png', confidence=0.8))
time.sleep(4)
pyautogui.click(pyautogui.locateCenterOnScreen('imagem_3.png', confidence=0.8))
time.sleep(4)
pyautogui.write('other', interval=0.1)
time.sleep(4)
pyautogui.press('enter')
time.sleep(4)
pyautogui.click(pyautogui.locateCenterOnScreen('imagem_7.png', confidence=0.8))
time.sleep(4)
pyautogui.press('enter')
time.sleep(4)
pyautogui.write(datainicio, interval=0.1)
time.sleep(4)
pyautogui.hotkey('tab')
time.sleep(4)
pyautogui.write(datafim, interval=0.1)
time.sleep(4)
pyautogui.press('enter')
time.sleep(4)
pyautogui.click(pyautogui.locateCenterOnScreen('imagem_8.png', confidence=0.8))
time.sleep(4)
pyautogui.click(pyautogui.locateCenterOnScreen('imagem_9.png', confidence=0.8))
time.sleep(4)
#nw4
pyautogui.click(pyautogui.locateCenterOnScreen('imagem_10.png', confidence=0.8))
time.sleep(4)
pyautogui.click(pyautogui.locateCenterOnScreen('imagem_3.png', confidence=0.8))
time.sleep(4)
pyautogui.write('NW4', interval=0.1)
time.sleep(4)
pyautogui.press('enter')
time.sleep(4)
pyautogui.hotkey('ctrl', 'l')
time.sleep(6)
pyautogui.click(pyautogui.locateCenterOnScreen('imagem_3.png', confidence=0.8))
time.sleep(4)
pyautogui.write('Textdown:XXINVM', interval=0.1)
time.sleep(4)
pyautogui.press('enter')
time.sleep(4)
pyautogui.press('enter')
time.sleep(4)
pyautogui.press('enter')
time.sleep(4)
pyautogui.click(pyautogui.locateCenterOnScreen('imagem_6.png', confidence=0.8))
time.sleep(4)
pyautogui.click(pyautogui.locateCenterOnScreen('imagem_3.png', confidence=0.8))
time.sleep(4)
pyautogui.write('other', interval=0.1)
time.sleep(4)
pyautogui.press('enter')
time.sleep(4)
pyautogui.click(pyautogui.locateCenterOnScreen('imagem_7.png', confidence=0.8))
time.sleep(4)
pyautogui.press('enter')
time.sleep(4)
pyautogui.write(datainicio, interval=0.1)
time.sleep(4)
pyautogui.hotkey('tab')
time.sleep(4)
pyautogui.write(datafim, interval=0.1)
time.sleep(4)
pyautogui.press('enter')
time.sleep(4)
pyautogui.click(pyautogui.locateCenterOnScreen('imagem_8.png', confidence=0.8))
time.sleep(4)
pyautogui.click(pyautogui.locateCenterOnScreen('imagem_9.png', confidence=0.8))
time.sleep(4)
#nwk
pyautogui.click(pyautogui.locateCenterOnScreen('imagem_10.png', confidence=0.8))
time.sleep(4)
pyautogui.click(pyautogui.locateCenterOnScreen('imagem_3.png', confidence=0.8))
time.sleep(4)
pyautogui.write('NWK', interval=0.1)
time.sleep(4)
pyautogui.press('enter')
time.sleep(4)
pyautogui.hotkey('ctrl', 'l')
time.sleep(6)
pyautogui.click(pyautogui.locateCenterOnScreen('imagem_3.png', confidence=0.8))
time.sleep(4)
pyautogui.write('Textdown:XXINVM', interval=0.1)
time.sleep(4)
pyautogui.press('enter')
time.sleep(4)
pyautogui.press('enter')
time.sleep(4)
pyautogui.press('enter')
time.sleep(4)
pyautogui.click(pyautogui.locateCenterOnScreen('imagem_6.png', confidence=0.8))
time.sleep(4)
pyautogui.click(pyautogui.locateCenterOnScreen('imagem_3.png', confidence=0.8))
time.sleep(4)
pyautogui.write('other', interval=0.1)
time.sleep(4)
pyautogui.press('enter')
time.sleep(4)
pyautogui.click(pyautogui.locateCenterOnScreen('imagem_7.png', confidence=0.8))
time.sleep(4)
pyautogui.write(datainicio, interval=0.1)
time.sleep(4)
pyautogui.hotkey('tab')
time.sleep(4)
pyautogui.write(datafim, interval=0.1)
time.sleep(4)
pyautogui.press('enter')
time.sleep(4)
pyautogui.click(pyautogui.locateCenterOnScreen('imagem_8.png', confidence=0.8))
time.sleep(4)
pyautogui.click(pyautogui.locateCenterOnScreen('imagem_9.png', confidence=0.8))
time.sleep(4)
pyautogui.click(pyautogui.locateCenterOnScreen('imagem_1.png', confidence=0.8))
time.sleep(2)





print("Automação concluída com exito")


